# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14pMMe3xYC-fuTLEBd4dg_K00lt-BT9UM
"""

import streamlit as st
import pandas as pd
import numpy as np
import yfinance as yf
from pytorch_forecasting import TemporalFusionTransformer
import lightning.pytorch as pl
from datetime import datetime, timedelta

# ==========================================
# 1. KONFIGURASI & LOAD MODEL
# ==========================================
st.set_page_config(page_title="CPO Intelligence Dashboard", layout="wide")
st.title("🌴 CPO Price Forecasting Dashboard (Hybrid Mode)")

@st.cache_resource
def load_model():
    # Pastikan file .ckpt hasil training kemarin ada di folder yang sama
    return TemporalFusionTransformer.load_from_checkpoint("tft_cpo_model_final.ckpt")

model = load_model()

# ==========================================
# 2. FUNGSI PENYIAPAN DATA (THE HYBRID ENGINE)
# ==========================================
def fetch_and_prepare_data():
    # A. Tarik Data Bursa (Live)
    # Kita tarik 45 hari terakhir biar aman buat rolling window 30 hari
    st.info("Fetching live market data from Yahoo Finance...")
    cpo = yf.download("FCPO.KL", period="45d")['Close'].reset_index()
    soy = yf.download("ZL=F", period="45d")['Close'].reset_index()
    oil = yf.download("CL=F", period="45d")['Close'].reset_index()
    myr = yf.download("MYR=X", period="45d")['Close'].reset_index()
    idr = yf.download("IDR=X", period="45d")['Close'].reset_index()

    # B. Load Data Cuaca (Historical/Static)
    # Untuk demo, kita asumsikan lu simpan data cuaca terakhir di CSV
    weather_df = pd.read_csv("historical_weather_data.csv") # File hasil scraping lu kemarin
    weather_df['Tanggal'] = pd.to_datetime(weather_df['Tanggal'])

    # C. Merging & Alignment
    # Gabungkan semua data berdasarkan Tanggal
    # (Di sini lu perlu nulis logika merge Pandas yang rapi)
    # ... proses merge ...

    # D. Feature Engineering (Rolling Sum & Time Features)
    # Hitung ulang 30D_Sum untuk cuaca dan fitur waktu (Bulan, dll)
    # ... proses rolling sum ...

    return df_final_processed # DataFrame siap suap ke model

# ==========================================
# 3. INTERFACE DASHBOARD
# ==========================================
col1, col2 = st.columns([1, 3])

with col1:
    st.subheader("Control Panel")
    if st.button("Run Live Prediction", type="primary"):
        with st.spinner("Calculating future probabilities..."):
            # 1. Siapkan data live
            # df_input = fetch_and_prepare_data()

            # 2. Jalankan Prediksi
            # preds = model.predict(df_input)

            # 3. Tampilkan Hasil
            st.session_state['pred_ready'] = True
            st.success("Prediction Complete!")

with col2:
    st.subheader("Price Prediction Analysis")
    if st.session_state.get('pred_ready'):
        
        # --- HAPUS st.write LAMA LU, GANTI JADI INI ---
        
        # 1. Kita bikin dummy data prediksi dulu (Nanti ini diganti pakai hasil model asli lu)
        tebakan = [4100, 4120, 4080, 4150, 4180, 4200, 4190]
        tanggal_depan = pd.date_range(start=pd.Timestamp.today(), periods=7).date
        df_hasil = pd.DataFrame({
            "Tanggal": tanggal_depan,
            "Prediksi Harga (MYR)": tebakan
        })
        
        # 2. Bikin Highlight Angka Penting di atas grafik
        col2_a, col2_b = st.columns(2)
        with col2_a:
            st.metric("Prediksi Besok", f"{tebakan[0]} MYR", delta="Tren Naik")
        with col2_b:
            st.metric("Puncak Tertinggi 7 Hari", f"{max(tebakan)} MYR")
            
        # 3. Tampilkan Grafik Garis (Line Chart)
        st.markdown("### Tren Harga 7 Hari Kedepan")
        st.line_chart(df_hasil.set_index("Tanggal"))
        
        # 4. Tampilkan Tabel Detailnya
        st.markdown("### Rincian Angka Harian")
        st.dataframe(df_hasil, use_container_width=True)

    else:
        st.info("Klik tombol 'Run Live Prediction' untuk memulai analisa.")

# ==========================================
# 4. EXPLAINABLE AI (XAI) SECTION
# ==========================================
st.divider()
st.subheader("Why is the price moving?")
# Tampilkan Bar Chart Variable Importance hasil interpret_output model
